### ISSUE TITLE
error on q.dump("statements.txt")

### ISSUE THREAD

**Issue by jazberna1** [schloi/MARVEL#28]
Hello,

I see the following in the do.py

` q.dump("statements.txt")`

at least in mi case line fails, as the dump method seems to be expecting a file handle, or at least that works for me.  This is the error message.

```
>>> q.dump("statements.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/jorge/marvel/lib.python/marvel/rawqueue.py", line 225, in dump
    fileOut.write(cmd + "\n")
AttributeError: 'str' object has no attribute 'write'
```

Thanks
Jorge

**Comment by sguizard** [comment]
Hi, I submitted a pull request for fixing this bug --> https://github.com/schloi/MARVEL/pull/29

**Comment by jazberna1** [comment]
Hello,

thanks so much
Jorge

On Wed, May 16, 2018 at 9:09 AM, Sébastien Guizard <notifications@github.com

**Comment by sguizard** [comment]
You're welcome
