### ISSUE TITLE
error in examples

### ISSUE THREAD

**Issue by yangxinchao** [schloi/MARVEL#8]
after i install the software , i have tested the software use the "examples/e.coli_pacbio". yet ,i had finished the first two steps , reporting the error below after i run "python3 do.py" ;
  `Traceback (most recent call last):
  File "do.py", line 44, in <module>
    q = marvel.queue.queue(DB_FIX, COVERAGE, PARALLEL)
  File "/ALNAS01/software/MARVEL/lib.python/marvel/queue.py", line 40, in __init__
    for strLine in open(self.db + ".db"):
FileNotFoundError: [Errno 2] No such file or directory: 'ECOL_FIX.db'`
anyone encounter this problem ?  this is very urgent ,wait online , thank you for your time ~

**Comment by schloi** [comment]
oi!

when did you checkout the code from the repository ? I fixed an error in that example yesterday.

**Comment by yangxinchao** [comment]
yes ,i download the repository the first day this month , l will check this again , thank you very much .
and another problem , when i run "autoreconf " ,report the error "autom4te: cannot lock autom4te.cache/requests with mode2: stale file handle " , i ignore this and run the next three steps(with no obvious errors) ,because i have not found the methods to deal with the problem .  i just want to know whether the two problem have  correlation , did you encounter this problem , wait for your answer ,thank you very much !

**Comment by yangxinchao** [comment]
yes， i change the "do.py" , the first problem does not show , i think it is the new script's contribution . but there is new  one 
`[1 8] daligner -v -I -t20 -e0.7 -r1 -j4 ECOL.1 ECOL.1
WARNING:root:command daligner not found. potentially using non-absolute paths
Traceback (most recent call last):
  File "do.py", line 40, in <module>
    q.process()
  File "/ALNAS01/software/MARVEL/lib.python/marvel/rawqueue.py", line 323, in process
    stdout = DEVNULL, stderr = subprocess.STDOUT),
  File "/home/yusheng/miniconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/yusheng/miniconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'daligner': 'daligner'`

**Comment by schloi** [comment]
The autoreconf error you are seeing has something to do with autoreconf somehow having problems when running on an nfs mount (on certain platforms). Nothing I can do about that on my end.

The other issue about the non-absolute path problem has been fixed with the commit referenced above. Essentially an argument defaulted to a wrong value. Never noticed that on my end due to the path to the binaries being included in my environment's PATH.

**Comment by yangxinchao** [comment]
First of all ,thank you very much for your answer , i have changed the " */marvel/rawqueue.py ", the process could run ,but there shows no error and no result , i show my process below : 
`[1 8] /ALNAS01/software/MARVEL/bin/daligner -v -I -t20 -e0.7 -r1 -j4 ECOL.1 ECOL.1
[2 8] /ALNAS01/software/MARVEL/bin/LAmerge -v -n 8 ECOL.db ECOL.1.las d001_00001
[3 8] /ALNAS01/software/MARVEL/bin/LAq -b 1 ECOL ECOL.1.las
[4 8] /ALNAS01/software/MARVEL/bin/TKmerge -d ECOL q
[5 8] /ALNAS01/software/MARVEL/bin/TKmerge -d ECOL trim
[6 8] /ALNAS01/software/MARVEL/bin/LAfix -g -1 ECOL ECOL.1.las ECOL.1.fixed.fasta
[7 8] !cat ECOL.*.fixed.fasta > ECOL.fixed.fasta
[8 8] /ALNAS01/software/MARVEL/scripts/DBprepare.py -s 50 -r 2 -j 4 -g 4600000 ECOL_FIX ECOL.fixed.fasta
[1 19 | 1 3] /ALNAS01/software/MARVEL/bin/daligner -v -I -t20 -e0.7 -r2 -j4 ECOL_FIX.1 ECOL_FIX.1
[1 19 | 2 3] /ALNAS01/software/MARVEL/bin/daligner -v -I -t20 -e0.7 -r2 -j4 ECOL_FIX.2 ECOL_FIX.2 ECOL_FIX.1
[1 19 | 3 3] /ALNAS01/software/MARVEL/bin/daligner -v -I -t20 -e0.7 -r2 -j4 ECOL_FIX.3 ECOL_FIX.3 ECOL_FIX.2 ECOL_FIX.1
[2 19 | 1 3] /ALNAS01/software/MARVEL/bin/LAmerge -v -n 8 ECOL_FIX.db ECOL_FIX.1.las d002_00001
[2 19 | 2 3] /ALNAS01/software/MARVEL/bin/LAmerge -v -n 8 ECOL_FIX.db ECOL_FIX.2.las d002_00002
[2 19 | 3 3] /ALNAS01/software/MARVEL/bin/LAmerge -v -n 8 ECOL_FIX.db ECOL_FIX.3.las d002_00003
[3 19 | 1 3] /ALNAS01/software/MARVEL/bin/LAstitch -f 50 ECOL_FIX ECOL_FIX.1.las ECOL_FIX.1.stitch.las
[3 19 | 2 3] /ALNAS01/software/MARVEL/bin/LAstitch -f 50 ECOL_FIX ECOL_FIX.2.las ECOL_FIX.2.stitch.las
[3 19 | 3 3] /ALNAS01/software/MARVEL/bin/LAstitch -f 50 ECOL_FIX ECOL_FIX.3.las ECOL_FIX.3.stitch.las
[4 19 | 1 3] /ALNAS01/software/MARVEL/bin/LAq -s 5 -T trim0 -b 1 ECOL_FIX ECOL_FIX.1.stitch.las
[4 19 | 2 3] /ALNAS01/software/MARVEL/bin/LAq -s 5 -T trim0 -b 2 ECOL_FIX ECOL_FIX.2.stitch.las
[4 19 | 3 3] /ALNAS01/software/MARVEL/bin/LAq -s 5 -T trim0 -b 3 ECOL_FIX ECOL_FIX.3.stitch.las
[5 19] /ALNAS01/software/MARVEL/bin/TKmerge -d ECOL_FIX q
[6 19] /ALNAS01/software/MARVEL/bin/TKmerge -d ECOL_FIX trim0
[7 19 | 1 3] /ALNAS01/software/MARVEL/bin/LArepeat -c 25 -b 1 ECOL_FIX ECOL_FIX.1.stitch.las
[7 19 | 2 3] /ALNAS01/software/MARVEL/bin/LArepeat -c 25 -b 2 ECOL_FIX ECOL_FIX.2.stitch.las
[7 19 | 3 3] /ALNAS01/software/MARVEL/bin/LArepeat -c 25 -b 3 ECOL_FIX ECOL_FIX.3.stitch.las
[8 19] /ALNAS01/software/MARVEL/bin/TKmerge -d ECOL_FIX repeats
[9 19 | 1 3] /ALNAS01/software/MARVEL/bin/LAgap -t trim0 ECOL_FIX ECOL_FIX.1.stitch.las ECOL_FIX.1.gap.las
[9 19 | 2 3] /ALNAS01/software/MARVEL/bin/LAgap -t trim0 ECOL_FIX ECOL_FIX.2.stitch.las ECOL_FIX.2.gap.las
[9 19 | 3 3] /ALNAS01/software/MARVEL/bin/LAgap -t trim0 ECOL_FIX ECOL_FIX.3.stitch.las ECOL_FIX.3.gap.las
[10 19 | 1 3] /ALNAS01/software/MARVEL/bin/LAq -s 5 -u -t trim0 -T trim1 -b 1 ECOL_FIX ECOL_FIX.1.gap.las
[10 19 | 2 3] /ALNAS01/software/MARVEL/bin/LAq -s 5 -u -t trim0 -T trim1 -b 2 ECOL_FIX ECOL_FIX.2.gap.las
[10 19 | 3 3] /ALNAS01/software/MARVEL/bin/LAq -s 5 -u -t trim0 -T trim1 -b 3 ECOL_FIX ECOL_FIX.3.gap.las
[11 19] /ALNAS01/software/MARVEL/bin/TKmerge -d ECOL_FIX trim1
[12 19 | 1 3] /ALNAS01/software/MARVEL/bin/LAfilter -n 300 -r repeats -t trim1 -T -o 2000 -u 0 ECOL_FIX ECOL_FIX.1.gap.las ECOL_FIX.1.filtered.las
[12 19 | 2 3] /ALNAS01/software/MARVEL/bin/LAfilter -n 300 -r repeats -t trim1 -T -o 2000 -u 0 ECOL_FIX ECOL_FIX.2.gap.las ECOL_FIX.2.filtered.las
[12 19 | 3 3] /ALNAS01/software/MARVEL/bin/LAfilter -n 300 -r repeats -t trim1 -T -o 2000 -u 0 ECOL_FIX ECOL_FIX.3.gap.las ECOL_FIX.3.filtered.las
[13 19] /ALNAS01/software/MARVEL/bin/LAmerge -S filtered ECOL_FIX ECOL_FIX.filtered.las
[14 19] /ALNAS01/software/MARVEL/bin/OGbuild -t trim1 ECOL_FIX ECOL_FIX.filtered.las ECOL_FIX.graphml
[15 19] /ALNAS01/software/MARVEL/scripts/OGtour.py -c ECOL_FIX ECOL_FIX.graphml
[16 19] /ALNAS01/software/MARVEL/bin/LAcorrect -j 4 -r ECOL_FIX.tour.rids ECOL_FIX ECOL_FIX.filtered.las ECOL_FIX.corrected
[17 19] /ALNAS01/software/MARVEL/bin/FA2db -c ECOL_FIX_CORRECTED [expand:ECOL_FIX.corrected.*.fasta]
[18 19] /ALNAS01/software/MARVEL/scripts/tour2fasta.py -c ECOL_FIX_CORRECTED -t trim1 ECOL_FIX ECOL_FIX.tour.graphml ECOL_FIX.tour.paths
` 
the files producted : 
`-rw-r--r--	1	root	PAG	98	Jan	30	17:23	README
-rw-r--r--	1	root	PAG	112M	Jan	30	17:23	p6.25x.fasta
-rwxr-xr-x	1	root	PAG	4.3K	Jan	30	17:23	do1.py
-rwxr--r--	1	root	PAG	4.3K	Feb	2	20:00	do.py
-rw-r--r--	1	root	PAG	158	Feb	3	16:26	ECOL.db
-rw-r--r--	1	root	PAG	48	Feb	3	16:26	ECOL.dalign.plan
-rw-r--r--	1	root	PAG	47	Feb	3	16:26	ECOL.merge.plan
-rw-r--r--	1	root	PAG	0	Feb	4	21:45	do.sh.o987844
-rw-r--r--	1	root	PAG	95	Feb	4	21:45	do.sh.e987844
-rw-r--r--	1	root	PAG	0	Feb	4	21:47	do.sh.o987845
-rw-r--r--	1	root	PAG	95	Feb	4	21:47	do.sh.e987845
-rw-r--r--	1	root	PAG	0	Feb	4	21:52	do.sh.o987848
-rw-r--r--	1	root	PAG	95	Feb	4	21:52	do.sh.e987848
-rwxr--r--	1	root	PAG	274	Feb	4	21:56	do.sh
-rw-r--r--	1	root	PAG	0	Feb	4	21:56	do.sh.o987849
-rw-r--r--	1	root	PAG	136	Feb	4	21:56	do.sh.e987849
-rw-------	1	root	PAG	4.0K	Feb	4	22:02	nohup.out
drwxr-xr-x	6	root	PAG	4.0K	Feb	4	22:10	OLD
drwxr-xr-x	2	root	PAG	4.0K	Feb	4	22:12	d001_00001
-rw-r--r--	1	root	PAG	73M	Feb	4	22:12	ECOL.1.las
-rw-r--r--	1	root	PAG	107M	Feb	4	22:12	ECOL.1.fixed.fasta
-rw-r--r--	1	root	PAG	107M	Feb	4	22:12	ECOL.fixed.fasta
-rw-r--r--	1	root	PAG	131	Feb	4	22:12	ECOL_FIX.db
-rw-r--r--	1	root	PAG	201	Feb	4	22:12	ECOL_FIX.dalign.plan
-rw-r--r--	1	root	PAG	165	Feb	4	22:12	ECOL_FIX.merge.plan
drwxr-xr-x	2	root	PAG	4.0K	Feb	4	22:12	d002_00003
drwxr-xr-x	2	root	PAG	4.0K	Feb	4	22:13	d002_00001
drwxr-xr-x	2	root	PAG	4.0K	Feb	4	22:13	d002_00002
-rw-r--r--	1	root	PAG	6.8M	Feb	4	22:13	ECOL_FIX.3.las
-rw-r--r--	1	root	PAG	34M	Feb	4	22:13	ECOL_FIX.2.las
-rw-r--r--	1	root	PAG	34M	Feb	4	22:13	ECOL_FIX.1.las
-rw-r--r--	1	root	PAG	6.8M	Feb	4	22:13	ECOL_FIX.3.stitch.las
-rw-r--r--	1	root	PAG	34M	Feb	4	22:13	ECOL_FIX.2.stitch.las
-rw-r--r--	1	root	PAG	34M	Feb	4	22:13	ECOL_FIX.1.stitch.las
-rw-r--r--	1	root	PAG	6.6M	Feb	4	22:13	ECOL_FIX.3.gap.las
-rw-r--r--	1	root	PAG	33M	Feb	4	22:13	ECOL_FIX.1.gap.las
-rw-r--r--	1	root	PAG	33M	Feb	4	22:13	ECOL_FIX.2.gap.las
-rw-r--r--	1	root	PAG	6.6M	Feb	4	22:13	ECOL_FIX.3.filtered.las
-rw-r--r--	1	root	PAG	33M	Feb	4	22:13	ECOL_FIX.2.filtered.las
-rw-r--r--	1	root	PAG	33M	Feb	4	22:13	ECOL_FIX.1.filtered.las
-rw-r--r--	1	root	PAG	71M	Feb	4	22:13	ECOL_FIX.filtered.las
-rw-r--r--	1	root	PAG	1.9M	Feb	4	22:13	ECOL_FIX.graphml
-rw-r--r--	1	root	PAG	2.8K	Feb	4	22:13	ECOL_FIX.tour.paths
-rw-r--r--	1	root	PAG	1.4K	Feb	4	22:13	ECOL_FIX.tour.rids
-rw-r--r--	1	root	PAG	3.5M	Feb	4	22:13	ECOL_FIX.tour.graphml
-rw-r--r--	1	root	PAG	5.2M	Feb	4	22:13	ECOL_FIX.corrected.00.fasta
-rw-r--r--	1	root	PAG	2.7M	Feb	4	22:13	ECOL_FIX.corrected.01.fasta
-rw-r--r--	1	root	PAG	1.7M	Feb	4	22:13	ECOL_FIX.corrected.02.fasta
-rw-r--r--	1	root	PAG	1011K	Feb	4	22:13	ECOL_FIX.corrected.03.fasta
-rw-r--r--	1	root	PAG	194	Feb	4	22:13	ECOL_FIX_CORRECTED.db
-rw-r--r--	1	root	PAG	0	Feb	4	22:13	ECOL_FIX.tour.fasta
`
need you help again ,  thank you ~

**Comment by phpeters** [comment]
Hej,

first and foremost: thanks for the tool! 
But I stumbled over the same issue as yangxinchao and suspect the pipeline to not finish (since only task 18/19 is done).

I re-ran the last command by hand and produced this error:

/software/MARVEL/scripts/tour2fasta.py -c ECOL_FIX_CORRECTED -t trim1 ECOL_FIX ECOL_FIX.tour.graphml ECOL_FIX.tour.paths
opening db ECOL_FIX
opening corrected db ECOL_FIX_CORRECTED
loading graph ECOL_FIX.tour.graphml
Traceback (most recent call last):
  File "/software/MARVEL/scripts/tour2fasta.py", line 468, in <module>
    main()
  File "/software/MARVEL/scripts/tour2fasta.py", line 460, in main
    process_graph(g, db, dbc, fileSeq, paths, track_trim_name, seqname_prefix)
  File "/software/MARVEL/scripts/tour2fasta.py", line 272, in process_graph
    eflags_prop = { e : g.edge[e[0]][e[1]]["flags"] for e in g.edges() }
  File "/software/MARVEL/scripts/tour2fasta.py", line 272, in <dictcomp>
    eflags_prop = { e : g.edge[e[0]][e[1]]["flags"] for e in g.edges() }
AttributeError: 'DiGraph' object has no attribute 'edge'

I am using Python 3.5.0 and networkx Version: 2.1

It seems that the edge-attribute was removed in the new networkx versions (see: https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html )

So I down-graded networkx to version 1.11, but just got a different error:
/software/MARVEL/scripts/tour2fasta.py -c ECOL_FIX_CORRECTED -t trim1 ECOL_FIX ECOL_FIX.tour.graphml ECOL_FIX.tour.paths
opening db ECOL_FIX
opening corrected db ECOL_FIX_CORRECTED
loading graph ECOL_FIX.tour.graphml
Traceback (most recent call last):
  File "/software/MARVEL/scripts/tour2fasta.py", line 468, in <module>
    main()
  File "/software/MARVEL/scripts/tour2fasta.py", line 460, in main
    process_graph(g, db, dbc, fileSeq, paths, track_trim_name, seqname_prefix)
  File "/software/MARVEL/scripts/tour2fasta.py", line 276, in process_graph
    track_source = db.track("source")
  File "/software/MARVEL/lib.python/marvel/DB.py", line 201, in track
    track = Track.from_db(self, tName)
  File "/software/MARVEL/lib.python/marvel/DB.py", line 115, in from_db
    assert( len(t.anno) == db.reads() + 1 )
AssertionError

Any ideas? Thanks for your help!
Philipp

**Comment by schloi** [comment]
I updated tour2fasta to networkx 2.x three days ago in commit https://github.com/schloi/MARVEL/commit/381b58acbbef619045dd10b8ac753ebb87473119. Note that the file gets generated when configure is run.

**Comment by yangxinchao** [comment]
hi , schloi ,i changed the 'touring/tour2fasta.py.in' , there also show no error and result  like before .

**Comment by phpeters** [comment]
Hej Siegfried,

I re-did autoreconf, configure, make, make install steps and it worked just well with the e.coli example. Thanks a lot!
ECOL_FIX.tour.fasta is then the final result, right?

Thanks again!
Philipp

**Comment by zhuyiqin** [comment]
I met the same issue as yangxinchao, and when I run the tour2fasta.py step alone, it shows these errors:
opening db ECOL_FIX
opening corrected db ECOL_FIX_CORRECTED
loading graph ECOL_FIX.tour.graphml
Traceback (most recent call last):
  File "MARVEL/scripts/tour2fasta.py", line 468, in <module>
    main()
  File "MARVEL/scripts/tour2fasta.py", line 460, in main
    process_graph(g, db, dbc, fileSeq, paths, track_trim_name, seqname_prefix)
  File "MARVEL/scripts/tour2fasta.py", line 276, in process_graph
    track_source = db.track("source")
  File "MARVEL/lib.python/marvel/DB.py", line 201, in track
    track = Track.from_db(self, tName)
  File "MARVEL/lib.python/marvel/DB.py", line 115, in from_db
    assert( len(t.anno) == db.reads() + 1 )
AssertionError

my networkx version is 2.1

Thanks!

**Comment by yangxinchao** [comment]
hi, zhuyiqin , you could try to download the new version and install again , maybe it is okey . i do it this mornimg , there is no error and  the result gets generated .

**Comment by zhuyiqin** [comment]
hi,
thanks for your suggestion. I tried it again and there is no error this time.

**Comment by schloi** [comment]
everybody seems to be happy .... time to close this issue
